# Generated by Django 5.2.8 on 2025-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('department', models.TextField()),
                ('salary', models.IntegerField()),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
